name: BoxPvP
version: '1.0-TESTING'
author: Andresq, fran2019
main: net.kappa.boxpvp.Main
api-version: 1.16

depends:
  - ProtocolLib

commands:
  claim:
    aliases: [ claimcreate ]
  claimremove:
    aliases: [ claimrem ]
  mine:
    aliases: [ minecreate ]
  message:
    aliases: [ msg, reply, r ]
  gamemode:
    aliases: [ gm ]
  discord:
    aliases: [ dc ]
  store:
    aliases: [ st ]
  teamspeak:
    aliases: [ ts ]
  twitter:
    aliases: [ tw ]